name: widget_to_image
description: A simple package to convert any of your widgets into an image.
homepage: https://github.com/nbrucker/widget_to_image

version: 1.0.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  lint: ^1.5.3

flutter:
